version: "3.9"
services:
  database:
    image: "postgres"
    networks:
      itsnetwork:
        ipv4_address: 10.0.0.12
    container_name: "dev-postgres"
    hostname: "dev-postgres"
    env_file:
      - ./env/database.env
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    networks:
      itsnetwork:
        ipv4_address: 10.0.0.13
    container_name: "dev-pgadmin"
    hostname: "dev-pgadmin"
    volumes:
      - pgadmin:/var/lib/pgadmin/
    ports:
      - 81:80
    env_file:
      - ./env/pgadmin.env
    depends_on:
      - database
    restart: always
  backend:
    image: arxway/nodeapp
    networks:
      itsnetwork:
        ipv4_address: 10.0.0.14
    container_name: "backend"
    hostname: "backend"
    depends_on:
      - database
    ports:
      - "1500:80"

volumes:
  data:
  pgadmin:
networks:
  itsnetwork:
    # name: itsnetworkTest
    driver: bridge
    # interface settings
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
